### ISSUE TITLE
Method names being cut in GUI list box

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/qMRLab#107]
I think this was possibly mentioned in a previous issue or at a lab meeting, but could we find a better solution for the naming convention and/or GUI style of the drop-down list for the methods names? As it is now, it goes /Category/Category/.../MethodName, meaning that every method name is is cut in the GUI:

![qmrlab_gui](https://user-images.githubusercontent.com/1421029/32616160-3993b366-c54c-11e7-97e1-a50a3fa67b26.png)

For example, switching from qMT SPGR to qMT SIRFSE results in the same same visible text in the list box above.

For users, I think the method being used should be immediately apparent (e.g. if someone took a screenshot of their processing session and sent it to someone, the other person should be able to replicate the settings, but they must be able to see the method being used). 

Maybe the solution would be to omit things like "Myelin Imaging" altogether in the GUI (and instead indicate it in the Doc?) and simply list the methods? Or, place the method name first in the list box, and then to the right of it the supporting information could be placed for beginner users when they use the drop down button?

**Comment by tanguyduval** [comment]
55d77aecb2a8026d91ba04036d8d21441bd7f818
