### ISSUE TITLE
[DOC] font of and style of menu changes for batch examples 

### ISSUE THREAD

**Issue by ileppe** [neuropoly/qMRLab#109]
On the rendered doc, the font and style of the menu changes when a batch example is loaded (it's really small!).

![screenshot 2017-11-09 16 16 43](https://user-images.githubusercontent.com/28764708/32630095-6c3faf78-c569-11e7-8939-e186368380b4.png)

A possible fix is to change the .html file explicitly after a publish, e.g. change the font size to 14. Would have to figure out what the font-family is...
`html body { height:100%; margin:0px; font-family:Arial, Helvetica, sans-serif; font-size:14px; color:#000; line-height:140%; background:#fff none; overflow-y:scroll; }`

**Comment by tanguyduval** [comment]
@zougloub we lack knowledge on html...
When we include raw html the font size is reduced in the left panel:
http://qmrlab.readthedocs.io/en/doc/CHARMED_batch.html
The menu should appear like that:
http://qmrlab.readthedocs.io/en/doc/documentation.html

The doc is generated using Sphinx. The corresponding restructured text can be found here:
https://github.com/neuropoly/qMRLab/blob/doc/docs/source/CHARMED_batch.rst

If you have any insight on why the font is reduced that would be very useful! Thanks

**Comment by zougloub** [comment]
If you check with "inspect element" on the tree you'll see that the style from the matlab dump is contaminating the rest of the page (as well as bringing non-compliance to HTML because of the nested `<html>`).
I'd suggest to preprocess the matlab-generated code using a small script (Python of course), that would strip the irrelevant nodes from the HTML tree and includes the syntax highlighting styles only.

**Comment by tanguyduval** [comment]
Thanks!
Can you plz clarify the lines that should be removed from this matlab-generated code:
https://github.com/neuropoly/qMRLab/blob/master/Data/CHARMED_demo/html/CHARMED_batch.html#L12

Attached is a copy that you can modify and send back.
[html.zip](https://github.com/neuropoly/qMRLab/files/1483416/html.zip)

**Comment by zougloub** [comment]
Please point to a git tree showing the issue... I could tell you to strip the lines 10 to 68 but that's just too ugly. Processing XML in your doc generation toolchain is the way to go, and I don't see such a thing in master.

**Comment by tanguyduval** [comment]
Issue in doc branch

**Comment by zougloub** [comment]
Thanks.
Here (https://github.com/zougloub/qMRLab/commit/d466f4db756fb5c8c513c8a25a8325d400b36ebf) is a suggestion: the makefile (it's not ideal but good enough) triggers generation of the rst file; the HTML file (assumed to follow the same template, which I didn't check) is stripped from header/footer, and a better-scoped CSS style is injected first.
If you use that, you can modify the Makefile to add the info for the other HTML files, which I didn't do.

**Comment by tanguyduval** [comment]
Thanks, embed_hmtl is very useful. 
Is it possible to keep:
- green for comments
- boxes for code
??
original:
![image](https://user-images.githubusercontent.com/7785316/32984060-cc303f56-cc6c-11e7-985c-1a51c756918c.png)
modified:
![image](https://user-images.githubusercontent.com/7785316/32984059-c3473160-cc6c-11e7-848e-cfcb0f2f3cf9.png)

**Comment by agahkarakuzu** [comment]
Beautiful! Hope it will be even better after automatic generation. :)

**Comment by zougloub** [comment]
@tanguyduval I made a mistake and committed something without testing it, and the styles weren't injected. It turns out that constructing a `StringIO` with data, then writing to it, is not appending by default.
You can take https://github.com/zougloub/qMRLab/commit/7dba26f76e56226a9d91cfa075fcf5519cf4fa26 if it works.

**Comment by tanguyduval** [comment]
Fabulous, thanks! I'll check that on Monday. You'll have a hooray emoji if it works on my side ;-)

**Comment by tanguyduval** [comment]
nicely working. @gab-berest can you integrate this change in your pipeline plz
