### ISSUE TITLE
ROI implementation-qMRLab

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/qMRLab#110]
Question from one of our user:
`````
Is there any way I can get the ROI option back on the GUI for qMRLab? 
`````

Yes, to do that, simply type `set(findobj('Tag','ROIPanel'),'Visible','on')` in the Matlab command line.

Best,
Tanguy

**Comment by mathieuboudreau** [comment]
Is there a section in the documentation for "FAQ/frequently asked questions"? This might be a good tip to put in the docs.
