### ISSUE TITLE
add logo (png and source) in repos under /logo

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/qMRLab#112]
@Agah

**Comment by mathieuboudreau** [comment]
I believe Agah's github username is actually @agahkarakuzu - he also doesn't seem to be assigned as a contributor in this repo (can't be assigned to this issue). @alexfoias could you add @agahkarakuzu as one?

**Comment by jcohenadad** [comment]
i added him already-- invitation pending

**Comment by agahkarakuzu** [comment]
Hello everyone, I did not get notifications from these mentions, I will recheck my settings. Leaving this comment here so that my user tag will appear.

**Comment by agahkarakuzu** [comment]
I am adding the logo here. On the other hand, I cannot see any pending requests in my account @jcohenadad 
![biglogo](https://user-images.githubusercontent.com/9632322/32692609-28d1d9d8-c6e9-11e7-8923-ae025abe4c57.png)

**Comment by jcohenadad** [comment]
No please don't put it here we'll have to do the cleanup. Let's put it directly where it should be

**Comment by agahkarakuzu** [comment]
Okay I will. Can you please send me invitation again?

**Comment by tanguyduval** [comment]
done in dcaa9ecc3fc08f511398a63d8ce1c36d870449cb
