### ISSUE TITLE
Rename SPGR --> qMT_SPGR

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/qMRLab#118]
I think that otherwise, it's confusing in the doc and in the scripts we are doing. That will only impact the batch that will need to be renamed also.
We need to do it now until it's too late.
Does anyone forsee some issue with that?

**Comment by tanguyduval** [comment]
I'll do that for all qMT methods

**Comment by mathieuboudreau** [comment]
I strongly agree with this change

A+

**Comment by tanguyduval** [comment]
717c53f81ca7e66971b9fafc807a299b32f7353f and 1d8afb76f9121b42cdbd375313c50ecb70fde206
