### ISSUE TITLE
Model hierarchy (directory structure)

### ISSUE THREAD

**Issue by ileppe** [neuropoly/qMRLab#119]
The current subdivisions are not entirely accurate (e.g. myelin imaging). We should probably only have 1 level and based on modality rather than application?
  * T1-relaxometry
     * inversion_recovery
     * vfa_t1
  * T2-relaxometry
     * mwf
  * Magnetization Transfer
     * qmt_spgr
     * qmt_bssfp
     * qmt_sirfse
     * mt_sat
     * mtr
  * Diffusion
     * charmed
     * noddi
     * dti
  * Fieldmaps
    * b0_dem
    * b1_dam
  * Noise
    * noise_level

**Comment by mathieuboudreau** [comment]
Great idea Ilana! 

You could maybe even subdivide fieldmaps into B0 and B1 (I don't have a great idea for their names beyond that). There is likely few B0 maps that will be implemented, but I can see having several B1 models in the future, considering there are so many "flavors" of those pulse sequences and it's still a highly developing field.

**Comment by ileppe** [comment]
@mathieuboudreau I don't know if we need different folders now (we can change this as the project grows), but how about
* Fieldmaps
  * B0_DEM
  * B1_DAM
  * B1_...

i.e. have the type of map 1st in the model name? Should make it clear?

**Comment by mathieuboudreau** [comment]
That sounds like a great compromise - I like it!

**Comment by mathieuboudreau** [comment]
@ileppe That sounds like a great compromise - I like it!
