### ISSUE TITLE
Add small description before TOC on index.html

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/qMRLab#125]
it feels more welcoming. Great inspiration here:
https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/userdoc/latest/index.html

**Comment by gab-berest** [comment]
I added this text:

Welcom to the user documentation for qMRLab, a quantitative MR image analysis open-source software. 
The modularity of the implementation makes it easy to add any additional modules and we encourage everyone to contribute their favorite recipe for qMR!

You can either read the Getting started section or search for the desired section.

Is it ok? @jcohenadad

**Comment by jcohenadad** [comment]
pls replace with:

Welcome to qMRLab, a software for quantitative MR image analysis. You can either read the Getting started [MAKE IT A LINK] or search for the specific qMR section.

thanks

**Comment by gab-berest** [comment]
Done! It's not visible in the documentation because redthedocs is not reponding when trying to build a documentation. But the description is in the document and ready to be transformed into a html file.

**Comment by ileppe** [comment]
@gab-berest is read the docs working now?

**Comment by tanguyduval** [comment]
@ileppe can you please add us to readthedocs with Agah also. currently you are the only owner and we cannot build:
![image](https://user-images.githubusercontent.com/7785316/33272614-ad2aa2a2-d358-11e7-85b6-bd20e1a92f88.png)

**Comment by ileppe** [comment]
ok, pls send me an e-mail with your readthedocs usernames

**Comment by tanguyduval** [comment]
@ileppe it's tanguyduval
