### ISSUE TITLE
Hiding some attributes and methods from user end 

### ISSUE THREAD

**Issue by agahkarakuzu** [neuropoly/qMRLab#126]
This can be simply achieved by defining methods/properties by passing Hidden key as true, without changing access permissions. Once we decide which ones are going to be shown, I can modify definitions.

**Comment by mathieuboudreau** [comment]
Is this to make the overall GUI more user-friendly? Maybe one idea could be to have a "basic" and "advanced" mode available, where basic would have several things hidden as you mentioned, and advanced would show all of the available ones.

**Comment by agahkarakuzu** [comment]
It is more to make CLI more user friendly. When dot operation is used, users can see only those related to them. 

Other attributes will still be there. For example, If one types Model.tf, still can access the field. I think help section can be complementary at this point. Otherwise it will require conditional object instantiation, I am not sure if this is possible in Matlab.

**Comment by mathieuboudreau** [comment]
Ok! Could you expand on what are some example methods/properties you think should be hidden from the GUI for certain models?

**Comment by agahkarakuzu** [comment]
For example (qMT_bSSFP), methods like GetProt, GetFitopt equation and attributes like buttons, xnames fit. @tanguyduval has the complete vision on this.

**Comment by mathieuboudreau** [comment]
Oh sorry I understand now - by CLI you meant command line interface, sorry I got confused!

**Comment by tanguyduval** [comment]
- hide `buttons` property
- hide all methods that are not described in qMRusage
 
`xnames` is informative, but shouldn't be modified by the user. Idem for `voxelwise`.
