### ISSUE TITLE
[SuperClass] Load/Save objects method

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/qMRLab#127]
Currently, we use `qMRloadModel` and `qMRsaveModel`.
These functions call `save` and `load` from Matlab.

Problem:
- Octave cannot load an object... So we cannot test retrocompatibility today :(
- If a class has been renamed (e.g. SPGR-->qMT_SPGR)... not compatible.

Solution:
Create a **superclass** for qMR models that includes methods `loadobj` and `saveobj` methods. saveobj should save a **structure** with all properties to ensure compatibility with Octave.
https://www.mathworks.com/help/matlab/matlab_oop/modifying-the-save-and-load-process.html

**Comment by agahkarakuzu** [comment]
By superclass do you mean like an abstract base class ? I guess we don't want anyone to create any object from that.

**Comment by tanguyduval** [comment]
Yes, an abstract base class that will be used to define the "common" lines.
Additionally, we should manage each methods' inputs in this superclass (e.g. `if nargin ==0, qMRusage(obj,'MethodName'); end `).
https://www.mathworks.com/help/matlab/matlab_oop/calling-superclass-methods-on-subclass-objects.html

**Comment by tanguyduval** [comment]
Currently, `equation_test.m` tries to load old models.

**Comment by mathieuboudreau** [comment]
@tanguyduval 

>**Additionally, we should manage each methods' inputs in this superclass (e.g. if nargin ==0, qMRusage(obj,'MethodName'); end).**

This is not clear to me. The superclass is not aware of the methods of its child classes/input, so would not be able to handle them in the superclass. What did you mean by that comment?

**Comment by tanguyduval** [comment]
cherry pick 5fcd4d54cc5db785b8c95ff8a44305970cdfb259 if you need

**Comment by tanguyduval** [comment]
Abstract class is complete. I added a small doc there https://github.com/neuropoly/qMRLab/wiki/Model

To add a new patch, create a method `qMRpatch` in the Model. Example
````
    methods(Access = protected)
        function obj = qMRpatch(obj,loadedStruct, version)
            % Call the patch of the AbstractModel (for generic patch that can be used for all models).
            obj = qMRpatch@AbstractModel(obj,loadedStruct, version);
            % ver < 2.0.6
            if checkanteriorver(version,[2 0 6])
                obj.MRIinputs = {'MTw'    'T1w'    'PDw'    'B1map'    'Mask'}; % add B1map
                obj.Prot.MT.Format(3) = []; % remove offset
                obj.Prot.MT.Mat(:,3)  = [];
                % add B1factor
                obj.buttons = {'B1 correction factor',   [0.4000]};
                obj.options.B1correctionfactor=0.04;
            end
            % ver < 2.0.8
             if checkanteriorver(version,[2 0 8])
              end
        end
    end
````
