### ISSUE TITLE
...done 0%

### ISSUE THREAD

**Issue by agahkarakuzu** [neuropoly/qMRLab#129]
I encounter this for some of the fittings such as B1_DAM. Even after successful termination, that 0% does not become 100%, which draws a confusing picture.

**Comment by tanguyduval** [comment]
#123 let's see that tomorow

**Comment by mathieuboudreau** [comment]
@agahkarakuzu I am getting this same bug for B0_DEM.

Although I can't confirm if the B0_DEM batch is working correctly, plotting the results gives me this for a B0 map...

<img width="1440" alt="capture d ecran 2017-11-23 a 17 23 31" src="https://user-images.githubusercontent.com/1421029/33188267-26507a8c-d073-11e7-8bce-a5607ff1c9c8.png">


Is this the expected result for this batch example?

**Comment by tanguyduval** [comment]
I think B0 issue was solved. 
B0_DEM looks like this:
![image](https://user-images.githubusercontent.com/7785316/34997858-d8658eda-fadd-11e7-82b6-c22c7d362842.png)
