### ISSUE TITLE
doc_Rename Batch Tests

### ISSUE THREAD

**Issue by agahkarakuzu** [neuropoly/qMRLab#133]
@ileppe After small changes, I have tested the following :

- b0_dem_demo
- b1_dam_demo
- inversion_recovery_demo
- mt_sat_demo
- mtv_demo
- mwf_demo
- noise_level_demo
- qmt_bssfp_demo
- qmt_sirfse_demo
- qmt_spgr_demo
- vfa_t1_demo

They all worked. I did not place generated batch examples in demo folders. Because they will change anyways :) 

I do not know if @tanguyduval  and @mathieuboudreau 's changes after 5.00pm will be suppressed if we merge this doc_rename to the doc  due to changes in filenames. I also don't know if there is a github practice for paired (upper_case <=> lower_case) replacement.

**Comment by mathieuboudreau** [comment]
Changes should not be suppressed between our branches as long as file renames were done using `git mv` and not `mv` or os-specific renaming methods. Everything should play nice through the merging process, git will know how to deal with the specifics and raise any potential conflicts that would need to be resolved.

If all else fails, we're only a few commits ahead.

**Comment by agahkarakuzu** [comment]
Thank you for the explanation @mathieuboudreau! So I should better remain as an observer for this one :)

**Comment by mathieuboudreau** [comment]
By looking at the commits, I don't see any issues that merging doc_rename to doc could cause my own Patch branch with commits from tonight - I can't speak for Tanguy's commit!

Looks like this mini-hackathon was a bit fruitful though!

**Comment by ileppe** [comment]
Thanks @agahkarakuzu adn @mathieuboudreau. I will push it, and keep our fingers crossed! I think the mini-hackathon was quite fruitful ;)

**Comment by ileppe** [comment]
@agahkarakuzu did you verity that the generation of the batch examples work or that the batch examples work? When I generate with `qMRgenBatch` and try to run the batch I am having issues:
* `qMRsaveModel` does not exist
* for `charmed`, we have to strip the `||` in the `Load Protocol` section
   * `% |G| (T/m) is a vector of [1791X1]
   * |G|  = [0.0000; 0.0000; 0.0000; 0.0000; 0.84...`

Please also commit the new batch examples, right now it's our only test for the models. Thanks!

**Comment by agahkarakuzu** [comment]
@ileppe This function is not intended for simulation models. It seems that the best option for sim batch examples is to edit them manually, because they don't fit into fit flow :)

**Comment by agahkarakuzu** [comment]
@ileppe should I commit them to doc_rename?

**Comment by agahkarakuzu** [comment]
@ileppe Edit (renamed) batch file examples to the Data folder. We can use these for testing till we adjust for downloading.

**Comment by tanguyduval** [comment]
@agahkarakuzu . Sorry, `qMRsaveModel ` was removed, we are going to use Matthieu's `Patch` branch.
branch `Patch` was extracted from `doc`. So when `Patch` is ready, we will merge it to `doc`. And then `doc` to `master`.
Same for `doc_Rename`. When ready, merge `doc_Rename` to `doc`.

**Comment by ileppe** [comment]
@tanguyduval `doc_rename` was already merged/pushed to `doc`
