### ISSUE TITLE
Non-interactive download from URL

### ISSUE THREAD

**Issue by agahkarakuzu** [neuropoly/qMRLab#139]
Hi @jcohenadad @tanguyduval @mathieuboudreau  and @ileppe 

MATLAB's websave function is working for downloading files from osf. The only drawback is that websave function was introduced in MATLAB R2014b. 

MATLAB cannot download via urlwrite due to public key certification issues (osf links are https). Adding osf certificate via matlab requires changes on file access settings in users' system and process is OS variant. This is why I think using websave in MATLAB is the safest option. You can try:

```
url = 'https://osf.io/u8n56/download/';
filename = 'charmed.zip'
location = websave(filename,url);
```
As for Octave, urlwrite works

`urlwrite('https://osf.io/u8n56/download/','charmed.zip')`

If minimum version requirement for MATLAB (R2014b) is not a problem, I will modify some class definitions and edit batch examples as we planned. 

I need commission approval to move on :)

**Comment by mathieuboudreau** [comment]
I don't see a problem with limiting Matlab versions beyond that version; most institutions provide licenses that allow for updates, and if the user doesn't have access they can simply use Octave. We just need to make sure to inform the users of this minimum requirement in the repo's README.

**Comment by tanguyduval** [comment]
Hi Agâh, use websave and change requirements in docs/source/documentation.rst (dependencies sectino)

**Comment by agahkarakuzu** [comment]
Alright @tanguyduval @mathieuboudreau . I'm on it.
