### ISSUE TITLE
OSF Data

### ISSUE THREAD

**Issue by agahkarakuzu** [neuropoly/qMRLab#142]
@jcohenadad @tanguyduval @ileppe  Hi all who has access to OSF ,

There are few issues :
* VFA_T1 files are missing
* Some of the files contain residuals files from previous outputs (FitTempResults etc).
* Can we also make sure that all zip files are compressed with/without a container folder to ensure consistency. 

Thank you so much.

**Comment by jcohenadad** [comment]
@agahkarakuzu should be added as admin on the OSF site

**Comment by tanguyduval** [comment]
@agahkarakuzu I just added you. I will add vfa_t1.

**Comment by agahkarakuzu** [comment]
Thank you @jcohenadad @tanguyduval . I'll organize file contents.

**Comment by agahkarakuzu** [comment]
I have updated all files and extracted just one slice for IR data.
