### ISSUE TITLE
Updated doc/video link on readme? 

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/qMRLab#145]
Are we still waiting on any updates to them before adding these to master for the potential ISMRM reviewer? If not we could branch master, add them to the readme file, and and make a pull request to merge back into master. (Right now the Documentation link still points to the master branch and not the doc branch of readthedocs)

**Comment by tanguyduval** [comment]
When  @agahkarakuzu is finished with the qMRgenbatch, we can run `GenerateDocumentation`, 
merge doc to master, and finally build the new doc on readthedoc. The video will be at the beginning of the doc.
@agahkarakuzu how long before we can generate all batch with Matlab (Octave is secondary). If >1week, we can do what @mathieuboudreau proposes.

**Comment by mathieuboudreau** [comment]
Oh ok, I was under the impression that the video deadline for today was important because the reviewers might get the abstract today and thus might start reading them over the weekend, but maybe I misunderstood Nikola (I am not a reviewer, so I'm not 100% sure when they get the abstracts).

@agahkarakuzu is the doc branch expected pass the build tests after that is done? We probably should only push doc to master after the branch is in a passing state, because if we do the reviewer will see that the build is in status "failing" on the repo page (see below, right now master is in a passing state).

e.g.
![qmrlab](https://user-images.githubusercontent.com/1421029/33508284-14b52298-d6d4-11e7-8665-1f774dce190f.png)

**Comment by tanguyduval** [comment]
ok @mathieuboudreau I used my administrator priviledge to solve this now.
Reload the doc page (webbrowser display old version otherwise)

**Comment by agahkarakuzu** [comment]
@tanguyduval @mathieuboudreau I was testing batch examples from beginning to the end. More than half way there, but octave is super time consuming in fitting. 

@tanguyduval Now that you are merging to master, how do you suggest me to proceed ?

**Comment by tanguyduval** [comment]
@agahkarakuzu I didn't merge the doc branch, I just added the nicest doc with the video. That will not impact your workflow. I didn't want to take a risk.

Use the new [BatchExample_Test](https://github.com/neuropoly/qMRLab/blob/doc/Test/MoxUnitCompatible/BatchExample_test.m) to develop faster. The environment variable ISTRAVIS skip the long fitting and you will see the bugs much faster. 

Great work btw

**Comment by agahkarakuzu** [comment]
Oh, ok. I still need to better understand Github mails. Alright, I will take that way! 

Thank you so much!

**Comment by mathieuboudreau** [comment]
Great, thank you both!

A+

Mathieu
