### ISSUE TITLE
[DOC] long lines not legible in batch examples

### ISSUE THREAD

**Issue by ileppe** [neuropoly/qMRLab#150]
The long lines like the references are illegible, the same goes for the big matrices:
![image](https://user-images.githubusercontent.com/28764708/35108345-508be9e0-fc41-11e7-9219-0d9f324687e4.png)

 I think the best would be an embedded scroll bar. @tanguyduval perhaps you could ask whoever wrote 'embed_html.py' to take a look at this? I am definitely not well versed enough in html.

**Comment by ileppe** [comment]
@TommyBoshkovski The scrolling seems to work great! If you are done implementing this can you make a pull request for your doc_tommy branch pls? We can then close this ;) Thanks.

**Comment by TommyBoshkovski** [comment]
Fixed in #184
