### ISSUE TITLE
Improve colorbar location & format?

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/qMRLab#153]
The current colorbar location (bottom) and format (small white font) is not really ideal for the eyes...

![35303549-e814a4c6-006c-11e8-8dd9-73902e18e66d](https://user-images.githubusercontent.com/1421029/35365392-ee9cb4e0-014e-11e8-91be-2ebbcc6d4f46.png)

I'm not sure when these choices were made, or if they are a legacy feature from qMTLab. Does anyone have any issue with positioning the colorbar outside the figure? I've made this and a few other minor changes to it in the branch `colorbar`:

![new](https://user-images.githubusercontent.com/1421029/35365518-903afcf8-014f-11e8-8c01-727fcd12c2a8.png)

**Comment by tanguyduval** [comment]
#155
