### ISSUE TITLE
Sensitivity analysis in GUI not working

### ISSUE THREAD

**Issue by ileppe** [neuropoly/qMRLab#157]
An error is thrown upon pressing the 'Update' button in sensitivity analysis:
`Error using length
Too many input arguments.`

Suggested change:
line 33 in SimVary.m `for pp=1:length(OptTable.fx)` changed to  `for pp=1:length(fx)`

**Comment by mathieuboudreau** [comment]
What model are you using? Does this error reproduce for all models?

**Comment by mathieuboudreau** [comment]
It'll be important to look into why this is missed by the TRAVIS tests too.

**Comment by ileppe** [comment]
It happens for all models. Digging deeper:
-  when called from the GUI `OptTable.fx` is a logical array, for which the `length` cannot be taken
- when called from the command line `OptTable.fx` is a regular array so no problem
This is why TRAVIS does not get tripped up. I think the fix I proposed would solve this, no?

**Comment by mathieuboudreau** [comment]
Sounds like it would! Might have been a minor bug introduced when switching from the old qMTLab GUI to the model-based GUI. I found a similar one recently dealing with masks.
