### ISSUE TITLE
qMT-spgr fixed pars

### ISSUE THREAD

**Issue by ravenep** [neuropoly/qMRLab#170]
As FYI - Default settings for the qMT-SPGR fitting routine fix both R1f and R1r to 1 in Fitting window. Default also checks “use R1 map to constrain R1f” in Fitting constraints. The output indicates that “use R1 map to constrain R1f” takes priority, as results for this par do not equal 1.

**Comment by mathieuboudreau** [comment]
Thanks @ravenep !

I agree, there is some confusion to how some of these options are displayed in the GUI. See issues #23 and #24 where this was brought up in the past. If I remember correctly, @jfcabana who coded qMTLab first set it such that if a parameter is constrained (e.g. use R1 map to constrain R1f), then the parameter "fix" box will also be checked, even though it is not exactly fixed to the value that is displayed in that table. This is a design issue which as you point out hasn't been resolved yet.

Now, that is how I understand the code works from the previous discussions, but if you feel like in addition there is a bug (e.g. T1 data not being used at all to constrain R1f), let us know too! The GUI design issue needs to also be cleared up in the near future, but the other case would be more urgent I believe.

p.s. I passed my defence =)

**Comment by ravenep** [comment]
Ok, great! I hadn't seen those previous comments. I do not think there is a bug, just potential for confusion if someone were not aware of this behavior. 

And YAY!!! Congrats, Dr. Boudreau! Well deserved 

![yas](https://user-images.githubusercontent.com/12449573/36736945-be3f13a4-1bd1-11e8-9d6e-bc292e156bd4.gif)

**Comment by mathieuboudreau** [comment]
No worries Erika, this is clearly an interface issue, since several users have encountered the confusion you described. I'm going to reopen the issue so it can be resolved in the (hopefully near) future.

And thanks!! =)
