### ISSUE TITLE
Problem with loading mask through GUI

### ISSUE THREAD

**Issue by agahkarakuzu** [neuropoly/qMRLab#171]
@HarrisNami  encountered this problem yesterday (R2014b) while trying to load mask for `mwf` via GUI. With batching, there was no problem with fitting using mask.  

In `mwf::fit` , if there is no mask, `multi_comp_fit_v2` is called by passing `'tissue', data.Mask ` (where data.Mask = 1) as varargin, which is originally intended for labeled masks I assume:

```
if isempty(data.Mask), data.Mask = 1; end
            [FitResults,Spectrum] = multi_comp_fit_v2(reshape(data.MET2data,[1 1 1 length(obj.Prot.MET2data.Mat)]), EchoTimes, DecayMatrix, T2, Opt, 'tissue', data.Mask);
```

There is another mask case in `multi_comp_fit_v2`  which is 'ROI'. Unless `fit` member function is overridden elsewhere, it is not likely that this option is used.  Might this have anything to do with  GUI failure ?

**Comment by ileppe** [comment]
We have trouble re-producing the error... seems to be fixed on error-catch.
