### ISSUE TITLE
GUI not supporting loading data from *.mat files anymore?

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/qMRLab#172]
The inversion recovery demo data is provided as *.mat files, however when I try to load them through the GUI, those files are greyed-out. 

![ir_mat](https://user-images.githubusercontent.com/1421029/36823091-f27b5998-1cd5-11e8-9a87-2b20702be8af.png)

@tanguyduval @agahkarakuzu , didn't we previously have the functionality to load data through *.mat files in addition to NIFTI files?

If so, is this missing functionality a "feature" that was recently implemented, or a bug? I didn't catch that change in a commit if it was intended, and feel like this is a bug, otherwise the TRAVIS tests should fail when loading these files right? 

Either way, I feel like we should allow this functionality (allow data from *.mat arrays), but if you guys decided that you want qMRLab to exclusively support NIFTI files, then we should ensure that all the demo data that we're providing is also in the NIFTI format.

**Comment by mathieuboudreau** [comment]
It looks from this block of code in BrowserSet that *.mat files are still intended to be supported,

https://github.com/neuropoly/qMRLab/blob/a7fed99293677379e90a27db4c4df56924ee4351/Common/tools/FileBrowser/BrowserSet.m#L107-L138

however this block of code is only executed *after* the file is chosen. I can't appear to find in the code where we're limiting the valid files in the file browser to be *.nii files, anyone know?

**Comment by tanguyduval** [comment]
@mathieuboudreau, this is not really a bug, but an interface design issue. If you click options (bottom left of the file browser), you will be able to select ".mat".
This is a known bug:
https://fr.mathworks.com/matlabcentral/answers/251141-uigetfile-dialogtitle-does-not-show-in-file-browser

**Comment by mathieuboudreau** [comment]
Thanks Tanguy! That interface issue was unknown to me, I didn't notice the change since I upgraded my Matlab.

Do you think we should have a way to inform users of this, since loading from mat files is a main feature? Do we mention it anywhere in the documentation? 

Maybe an FAQ or Troubleshooting section could be useful?

**Comment by tanguyduval** [comment]
I would change call to `uigetfile`in `BrowserSet.m` to accept both .mat and .nii and detect the type of input afterward. That would solve this issue
