### ISSUE TITLE
qMRgenBatch is broken for all models in Matlab

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/qMRLab#173]
Trying to generate batch functions for any models results in this error on MATLAB  2017a and a Macbook Pro:

```matlab
>> qMRgenBatch(mwf, 'tmp/')
Please wait. Downloading data ...
Data has been downloaded ...
Output argument "dataPath" (and maybe others) not assigned during call to
"downloadData".

Error in qMRgenBatch (line 47)
demoDir = downloadData(Model,path);
```

Anyone have an insight on how long has this bug been in here, and why wasn't it caught by TRAVIS? I thought TRAVIS tested the batch generations?

**Comment by tanguyduval** [comment]
@mathieuboudreau solved in d76ba8f2b5deb7abd55fa410e6de2dca1a2c497d
Issue was raised with relative path, but it was working with absolute path (e.g. `qMRgenBatch(mwf, pwd)`)

**Comment by mathieuboudreau** [comment]
Hmmm ok thanks. Both the headers of downloadData and qMRgenBatch should be changed inform this to the user in that case, because currently downloadData has no header at all and qMRgenBatch only says:

```
% This function generates a batch example script. based on template: genBatch.qmr
% qMRgenBatch(Model,path)
```

and doesn't provide details about how `path` needs to be given.

**Comment by tanguyduval** [comment]
@mathieuboudreau with d76ba8f it is now working with relative path. But I agree we need to improve the header

**Comment by mathieuboudreau** [comment]
Ahhh sorry I got confused, too early in the morning for me :S , thanks! 

On a side note, I think that fix would have been useful enough in its own branch and pushed to master immediately, instead of including it in `error-catch`. Now I have to wait for `error-catch` to be merged :P

**Comment by tanguyduval** [comment]
No worries. Sorry for the wrong push, don't hesitate to cherry pick this commit ;)
