### ISSUE TITLE
DTI module 

### ISSUE THREAD

**Issue by ileppe** [neuropoly/qMRLab#176]
Issues specific to DTI model
- [x] The header of the model needs to be completed/fixed
- [x] the sample data provided for `dti_batch` takes for ever to fit, should add option for simpler fit
- [x] The default map that shows up on the documentation is `residue`, I think `FA` would be more informative

**Comment by ileppe** [comment]
Weighted-Average + linear fit:
Pros:
- Does not require exact SNR measure
- No assumption on noise characteristic (e.g. Rician or Non-central Chi)
Cons:
- Only an approximation (not a perfect solution), which is problematic if the entire dataset is low SNR (e.g. high b-value diffusion dataset).

Non-linear fitting (objective function = rician likelihood)
Pros:
- perfect solution
Cons:
- Assumes noise characteristic (e.g. Rician) 
- Need to compute SNR
- Slow

Rician bias correction + linear fit:
Pros:
- Close to the perfect solution (We correct rician bias assuming: noisy signal = expected signal)
Cons:
- Need to compute SNR
- Assumes noise characteristic (e.g. Rician) 

We can usually assume that noise is Rician because most people use "adaptive combine"
SNR can be computed easily using ~5 repetitions of the same measure.

NOTE 1: THIS DISCUSSION IS VALID FOR ALL VOXELWISE MODELS (although high SNR datasets do not suffer much from rician bias)
NOTE 2: THE NOISE IMPACT ON THE FITTED METRICS CAN BE ASSESSED USING SENSITIVITY ANALYSIS.

**Comment by tanguyduval** [comment]
done in #180
