### ISSUE TITLE
[user] noMT Normalization

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/qMRLab#177]
Question from a user:

````
Hi Tanguy, 

I'm looking to see if its possible to remove the normalization when solving for the qMT fit? The reason being is that I did not acquire data for noMT. 

Thank you for your time.  
````

In **qmt_spgr**, 
MTdata are normalized by the volume acquired at Angle = 0;
If the protocol does not present any MToff (Angle = 0), qMRLab assumes that MTdata are already normalized and fits the dataset without normalization (e.g. see example dataset):
**Case 1: without Angle = 0** --> no normalization
![image](https://user-images.githubusercontent.com/7785316/37022216-921e1b3e-2122-11e8-86aa-2399128a2189.png)
**Case 2: last volume is MToff (Angle = 0)** --> last volume is used to normalize dataset
![image](https://user-images.githubusercontent.com/7785316/37022289-ca6a4404-2122-11e8-9260-006e9a9fda6c.png)

Note: you can check the fitting using the `view data fit`button

In **qmt_sirfse**,
The signal at MToff is a fitting variable: `M0f`
qMRLab normalizes using the max signal (i.e. usually the longest inversion time) and then adjust the residual error

Happy to help,
Best
Tanguy

**Comment by mathieuboudreau** [comment]
@tanguyduval Hmmm, I don't recall seeing anyone do that in the literature, I would have to check deeper. Off the top of my head, one issue that I would think they would encounter is is that there will be spacial variability due the spatial receiver sensitivity, which would also need to be fitted for, and I doubt that would be stable unless more qMT data points are acquired (which in that case, why not acquire the no-MT pulse).

One option they could tryif this was just a mistaken omission of that acquisition is to normalize the data by their MT-on pulse that is the farthest off-resonance and lowest flip angle; if they've acquired at an off-res far enough, it might be good enough for a decent fit (see the blue curve in your first figure, at ~17kHz the normalized signal is almost 1).

p.s. Is that data a phantom or a tissue/subject? If it's the latter, the curves look irregular from what I would generally expect. If it's the former (e.g. an agar phantom), then they should not be using the Super-Lorentzian lineshape for fitting, but Gaussian for agar.

**Comment by tanguyduval** [comment]
Thank you Mathieu, I think you answer the user question.
Concerning the curve, I took it from the in-vivo example dataset (`qMRgenBatch(qmt_spgr,pwd)`) somewhere in the WM, just to illustrate. Feel free to check the quality of this dataset, and submit a better dataset if necessary.

**Comment by mathieuboudreau** [comment]
Thanks Tanguy!!

Actually now that I've taken a second look at it, I think the data is fine, it's just that it's not plotted on a semi-log scale (for the x-axis) as z-spectrums are typically done. I think the spectrum appears more Lorentzian/Gaussian because it's plotted on a linear scale.
