### ISSUE TITLE
Rendre qMTLab modulaire

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/qMRLab#20]
Dans l'idéal, il faudrait pouvoir ajouter n'importe quel model (e.g. MTSAT / Diffusion), et pouvoir toujours bénéficier de la partie Simulation qui est très bien faite + fitting + génération des cartes.

Par exemple créer un dossier dans lequel on met tous les models. C'est à dire des script matlab qui prennent en entrée (1) variables à fitter (2) fichier de parametre d'acquisition (offsets + FA, ou bvalue + bvecs) et qui sortent (1) Signal IRM et (2) nom des variables.

Cela serait-il possible facilement tu crois JF??!! Bref je lance l'idée ici.. à développer..
Tanguy

**Comment by jfcabana** [comment]
L'idée est intéressante, mais demanderais certainement passablement de travail. À la question "Cela serait-il possible facilement", je dirais possible mais pas si facilement :P De la façon dont le code est fait, c'est assez "facile" disons d'ajouter des modèles qMT basés sur le two-pool. La structure des fonctions est la même pour tous les modèles, on peut donc se baser sur ce qui est déjà là et faire du copier coller en adaptant au besoin. Intégrer ça dans l'interface graphique demande un peu plus de travail par  contre, et je ne crois pas que ça soit possible d'automatiser cette partie. Chaque modèle a ses particularités propres qui requiert une interface d'options adaptées. S'il y a d'autres modèles qMT à intégrer je serais heureux de vous aider à y travailler, mais de rendre ça complètement automatisable juste en copiant des dossiers de fonctions, je ne suis pas sûr d'y arriver. Chose certaine le code est assez flexible pour permettre de l'adapter à d'autres sauces.

Pour ce qui est d'inclure d'autre types d'imagerie, i.e. diffusion, il faudrait voir quels modèles théoriques existent dans ce cas, je ne suis pas familier avec la simulation de ces données. Ça demanderait plus de travail de ce côté là par contre, car pour l'instant la simulation est uniquement basées sur les équations de Bloch modifiées avec un coupling entre 2 pool, spécifiquement la description de MT de Henkelman. Les modules de simulation et fitting pourraient certainement être adaptés à d'autre modèles en réutilisant certaines fonctions, mais demanderaient surement pas mal de modifications...

**Comment by tanguyduval** [comment]
Merci pour la réponse détaillée JF! 

Je comprends que ça sera difficile de rendre les fonctions actuelles modulaires. Peut-être peut-on faire en sorte que toute nouvelle entrée dans le menu "Choose Method" soit modulaire (i.e utiliser les même fonction pour toutes les autres méthodes). 
- Pour les simulation on peut juste utiliser l'équation du modèle fourni (et non pas simuler un steady state basé sur les équations de block ).
- Pour les options on peut garder les panneaux Simulation et Fitting pour tous les nouveaux modèles. Le panneau Protocol par contre il faudra demander de charger une matrice des paramètres d'acquisition qui sont variés --> Par exemple dans le cas de MTSat, la ligne i de cette matrice correspondra à TR / TE / FA / MT_offset du volume i.

On peut voir ça après la soumission ISMRM!
Tanguy

**Comment by tanguyduval** [comment]
Ok la branche CustomMethod  est presque prête avec 3 méthodes de diffusion: CHARMED / NODDI / DTI
Ils manque qques petites choses à éclaircir:
[ ] Intégrer la modification dynamique du browser de fichiers pour ne pas avoir toujours data / mask / B1map / B0 map...  @BeliveauP travaille dessus
[ ] Il y a une dépendance à NODDI (http://mig.cs.ucl.ac.uk/mig/mig/index.php/?n=Tutorial.NODDImatlab/)... Pour l'instant il y a un test pour voir si elle est installée
[ ]  Avec beaucoup de nouveaux models ça devient fouillis. Je voulais mettre des sous-menus (e.g. qMT / Diffusion) dans le popupmenu "MethodMenu" mais ce n'est pas possible.. C'est possible uniquement dans les menus en haut de la figure. À voir comment gérer l'interface pour que ce soir toujours aussi user friendly...

**Comment by tanguyduval** [comment]
À noter qu'un nouveau model ressemble à ça:

`````
classdef CHARMED
    properties
        MRIinputs = {'MTdata','Mask'};
        xnames = {'fh','Dh','diameter_mean','fcsf'};
        
        % fitting options
        st           = [0.6     0.7        6       0.2          ]; % starting point
        lb            = [0       0.3        3          0               ]; % lower bound
        ub           = [1       3         10         1                ]; % upper bound
        fx            = [0      0           0           0               ]; % fix parameters
        
        % Protocol
        ProtFormat = {'Gx' 'Gy'  'Gz'   '|G|'  'Delta'  'delta'  'TE'}; % columns of the Protocol matrix. 
        Prot  = [ones(100,1) zeros(100,2) linspace(0,300,100)'*1e-3 0.040*ones(100,1) 0.003*ones(100,1) 0.070*ones(100,1)];
        
        % Model options
        buttons = {'Dcsf',3,'Dr',1.4,'Sigma of the noise',10,'Compute Sigma per voxel',true};
        options= struct();

    end
    
    methods
        function Smodel = equation(obj, x)
        end
        
        
        function FitResults = fit(obj,data)
        end
        
        function plotmodel(obj, x, data)
        end
end
`````
