### ISSUE TITLE
[User Bug] qMRLab fails to load GUI for user

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/qMRLab#202]
@ravenep encountered this bug when trying to load qMRLab (master – downloaded via the 'Clone or download' button)

*Error using cell/strfind (line 32)*

*If any of the input arguments are cell arrays, the first must be a cell array of strings and the second must be a character array.*

<img width="644" alt="screen shot 2018-04-23 at 5 40 06 pm-2" src="https://user-images.githubusercontent.com/1421029/39141475-7ff8f75c-4702-11e8-8901-cc5f59c080c8.png">

She says that she does not receive this error if she downloads Release # 2.1.0, which is 20 commits behind.

Operating system: 

NAME="CentOS Linux” 
VERSION="7 (Core)” 
ID="centos” 
ID_LIKE="rhel fedora” 
VERSION_ID="7" PRETTY_NAME="CentOS Linux 7 (Core)" 

MATLAB version (to be updated soon I hope) - 2015a

**Comment by mathieuboudreau** [comment]
I'm able to open the qMRLab GUI with no issue on:

- OSX Sierra 10.12.6 & MATLAB 2017a
- OSX El Capitan 10.11.6 & MATLAB 2015b

@ravenep I'm going to try and create a VirtualBox with your specific OS and try to install MATLAB on it to see if I can reproduce your issue.

@tanguyduval you played around with this file for the recent GUI-fixes PR (see [here](https://github.com/neuropoly/qMRLab/commits/71e509f76b570b24be8d28058a1b0b1f141feb2b/Common/iqmr_header.m) for file history), do you have any insight on why Erika might be encountering this issue on [this line](https://github.com/neuropoly/qMRLab/blob/5f6d9f4d2dacfc43e62c74bf627d095c40e3cb3c/Common/iqmr_header.m#L133) on master? @gab-berest too?

**Comment by gab-berest** [comment]
I'll try to recreate the error later tonight. However, I don't understand when does it happen. When you try to run the main GUI?

**Comment by gab-berest** [comment]
I just tried to reproduce the error on Windows and it doesn't appear to be a problem. Is there something that is done when booting up the program or is it just by trying to run it?

**Comment by gab-berest** [comment]
@mathieuboudreau I think I've found the problem. When using the fields(i) in Matlab earlier versions, it returns a cell array of character instead of a character array and the strfind cannot take this argument. Before changing anything, I would like a a feedback. Changing the line to 133 in iqmr_header.header_parse to:

finds = strfind(lower(line),lower(char(fields(i))));

To change the cell array to a character array. It works on my end, but I'm not sure that it's the problem and I cannot reproduce it. Can you confirm what I'm saying?

**Comment by mathieuboudreau** [comment]
Thanks for looking into this @gab-berest !

This isn't a problem I experienced myself; it's one that Erika emailed me about experiencing on her end. I'll paste the email exchange I had with her below.

I haven't reproduced the error myself yet; I created a VirtualBox image of CentOS 7 and am installing Matlab 2015a at the moment (slowly...) to test it using her setup. I'll let you know if I'm able to reproduce it and/or solve it with your info.

```
Hi Mathieu, 

I stepped away from the MT analysis for awhile, but came back to it this weekend and immediately got an error… It could be something simple, but I just wanted to ask if you’ve seen a similar error (pic below). I am using qMRLab-2.1.0 and the qmt_spgr module. I was able to run the fitting before, but unfortunately lost my previous software download and had to replace. The newest GitHub version did not open for me, so I have this one. 

As FYI, I had a data set with a singleton dimension for the slice (x,y,z,mtvol), and tried it with and without this. Still got the same error. 

Cheers, 
-e 

```
![1ba7b1aa38be4d52abd1bb1a7ffc5fe6](https://user-images.githubusercontent.com/1421029/39213055-1a01721e-47eb-11e8-988f-ddd96e5620b0.png)

```
Hi Erika,

I haven't seen this error before – do you mind posting this in a GitHub issue?

> The newest GitHub version did not open for me, so I have this one. 

Could you clarify on this latter point? You downloaded the latest GitHub version and the GUI didn't open?

Best,

 
Mathieu
```

```

Hi Mathieu, 

RE: the latest version - I downloaded the ZIP via ‘clone or download’ button on the main page. Added the qMRLab-master to path w/ subfolders. Typed ‘qMRLab’ in Matlab command window to load GUI. Then got the error below. This did not happen with 2.1.0 so have been using that (but with other issue)
```

![e442ef660cfa45b4a76288f31a5f27e6](https://user-images.githubusercontent.com/1421029/39213134-4e6781ba-47eb-11e8-8844-d07f49591198.png)

```
Thanks Erika! I just tried opening the qMRLab GUI by downloading via the 'clone or download' button myself, but did not encounter that error.

Would you mind sharing your operating system information (name & version) as well as your MATLAB version?

Best,

Mathieu
```

```
Hi Mathieu, 

Operating system: 

NAME="CentOS Linux” 
VERSION="7 (Core)” 
ID="centos” 
ID_LIKE="rhel fedora” 
VERSION_ID="7" PRETTY_NAME="CentOS Linux 7 (Core)" 

MATLAB version (to be updated soon I hope) - 2015a


-e

```

**Comment by gab-berest** [comment]
No problem. When you have tested it you can update me so I'll make the changes if it is this issue.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau cool pick out, I was not expecting that! qMRLab is lucky to have someone who has nerves to test it across platforms and MATLAB versions: **Mathieu CI** :)

**Comment by mathieuboudreau** [comment]
@agahkarakuzu ahahaha. I'm just lucky that McGill's MATLAB license allowed me to download any previous version that I wanted/needed ;)

So odd though that 2015b (which was on my old MacBook, that I tested this morning) was that one version that changed the strfind() functionality lol.

@gab-berest great fix suggestion! Wrapping the second argument of strfind() did the trick. This function is called in several other locations in the file, but repeating the fix everywhere in that file allowed me to finally open the GUI on CentOS Linux 7 and MATLAB 2015a. I'll commit those changes, but test fitting few of the demo data and maybe simulations before making the pull request.

**Comment by mathieuboudreau** [comment]
Working on branch: [bug_matlab2015a](https://github.com/neuropoly/qMRLab/tree/bug_matlab2015a)

**Comment by agahkarakuzu** [comment]
@mathieuboudreau Because my version is.. wait for it.. R2015b 😀 I remember dealing with many string vs cell issues those makes no sense by definition but affects the functionality. Is this what you mean by 

> Wrapping the second argument of strfind() did the trick.

**Comment by agahkarakuzu** [comment]
> You wrapped thisJoker with curly braces to make it a cell, but this in fact breaks for version <2015b (see all the way on top here for example of error message).

Interestingly, I've never run into an error because of this on my local. If it is truly trivial irrespective of the OS/MATLAB version combinations, then they were my scare curly braces (unnecessary placed in that case) because of the issues I was dealing with the proper string replacement in absence of 'contains' function.  In addition, I was trying to give robustness against the casting heterogeneity in the MRIinputs attribute, which sometimes was a string. Which is why I added:  

> MRIinputs is a 1xN cell array for N input files.

And I remember that at I was getting different empty cell definitions caused by a variable's being casted as char. Although it was not giving me a runtime error, it was hampering the output.

**Comment by mathieuboudreau** [comment]
Ahh I see, that makes sense!

A+

**Comment by ravenep** [comment]
Hi everyone, I downloaded the most recent qMRLab and the GUI works! Thanks @mathieuboudreau @agahkarakuzu @gab-berest et al for working on this issue. I can't imagine how you deal with all these combinations of platforms. 

Happy user here!

**Comment by ravenep** [comment]
Another update -  using the new version (that was made compatible with 2015a) has bypassed the other issue where the fitting output was not being saved. 

I am now even more happy. Thanks all

**Comment by mathieuboudreau** [comment]
Excellent! This bug fix was a 2-for-1 deal, I'm happy it's working for you!
