### ISSUE TITLE
[DOC] Create a pull-request review guideline

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/qMRLab#213]
As mentionned in PR #212 , and having encountered it in a few other PRs, I think we should decide on a guideline of things to check before approving PRs. This is particularly important so that the GUI is constantly tested, which it isn't in the Travis tests.

Something like this could look like.

- Ensure Travis tests passed.
- Ensure coverage.io did not drop by more that 1 % (preferably not at all). 
- Read over the files changes.
    - If some of the file changes are not covered by tests (see https://coveralls.io/github/neuropoly/qMRLab), test manually through the GUI or on the command line.
- Test that the GUI opens.
- Using the test data of a model (e.g. VFA), test:
    - Loading the data
    - Plotting the data
    - Fitting the data
    - ???

Anything else we should add?

**Comment by mathieuboudreau** [comment]
@agahkarakuzu @ileppe After reviewing a few more PR's, here are the guidelines I propose for the wiki. Do you agree with them?

<p>
<p>
<p>

**Ensure that branch is up-to-date with master**
* If not, merge master into the branch
* Carefully identify and review any changes in compiled/binary files – particularly important for .fig files. If the master included any changes in these after the PR was branched, then you'll have to identify and manually merge the new elements of the PR into the master one (NOT chose one file over the other).

**Travis tests pass?**
* If not, resolves bugs/issues that caused the fail.

**Coveralls.io condition pass?**
* Fails if coverage drops by more than 1%
* If it fails, write more tests that cover the new code from the branch.

**Review that changed source files/lines are related to the pull request/issue**
* If any files/commits were accidentally included, cherry-pick them into another branch.

**Review that changed source files/lines were not accidentally deleted**
* Fix appropriately if so.

**Test new features or bug fix**
* If not implemented/resolved adequately, solve it or inform the developper by requesting changes in your review.
* Preferably, set breakpoints in the locations that the code was changed and follow allong line by line to see if the code behaves as intended.

**Manual GUI tests (general)**
* Does the qMRLab GUI open?
* Can you change models?
* Can you load a data folder for a model?
* Can you view data?
* Can you zoom in the image?
* Can you pan out of the image?
* Can you view the histogram of the data?
* Can you change the color map?
* Can you fit dataset (Fit data)?
* Can you save/load the results?
* Can you open the options panel?
* Can you change option parameters?
* Can you save/load option paramters?
* Can you select a voxel?
* Can you fit the data of that voxel (Single Voxel Curve)?
* Can you run a Sensitivity Analysis?
* Can you simulate a Multi Voxel Distribution?

**Comment by spinicist** [comment]
Hi,

A tip on the first point - `git rebase` or `git rebase --interactive` is a much cleaner way of ensuring your branch is up to date with master. It avoids the history being peppered with merge commits. Some people might find those clearer, but I find them annoying as hell.

**Comment by mathieuboudreau** [comment]
Thanks @spinicist! I think for our case that's not a big issue at the moment, as we have it up to squash and merge PRs by default anyways. But that'll be something to keep in mind if we go back to simple merges of PRs.

**Comment by mathieuboudreau** [comment]
Added the guidelines here: https://github.com/neuropoly/qMRLab/wiki/Guideline:-Reviewing-a-pull-request

Feel free to make any changes in the wiki, or re-open this issue to give any more suggestions for changes/additions.
