### ISSUE TITLE
[BUG] qMRLab "save fitting options" button incompatible with users called "Mathieu"

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/qMRLab#217]
...either that, or there's a wild regex pattern that removes all "mat" instances in the full directory path of the file it saves, as well as the character preceeding it. :sparkles:

![1](https://user-images.githubusercontent.com/1421029/40148547-17d748aa-5949-11e8-9ac2-49dead4a0d01.png)
---
![2](https://user-images.githubusercontent.com/1421029/40148551-1c157f4a-5949-11e8-8015-3a1780c9e36b.png)
---
![3](https://user-images.githubusercontent.com/1421029/40148554-1e099b56-5949-11e8-9920-cce32b5e0d9b.png)
---
![4](https://user-images.githubusercontent.com/1421029/40148588-53022ad0-5949-11e8-80de-cc867b86bab9.png)

**Comment by tanguyduval** [comment]
Ahah, I love this bug! 
solved in 43a5cf1925f1edb2f38d2b140fc33be386b89a37

**Comment by mathieuboudreau** [comment]
I reopenned this because we should keep issues opened until they've been merged into master (so that people are aware of the current bug in master). These should automatically be closed when the Pull Request are merged by giving the following as a description of the Pull Request ("Resolved issue #(issue number)".
