### ISSUE TITLE
ROI tool crashes after deleting an ROI and trying to add new one

### ISSUE THREAD

**Issue by HarrisNami** [neuropoly/qMRLab#223]
After adding an ROI, and then deleting that ROI, if I go to add another ROI, it will allow me to create a new one, but then the box in the left corner disappears (as shown in the screenshot) and I have to quit and restart the tool.

![screen shot 2018-05-22 at 2 13 26 pm](https://user-images.githubusercontent.com/29234406/40381846-c8620888-5dca-11e8-9ae8-995cd24b92a5.png)

**Comment by mathieuboudreau** [comment]
@HarrisNami could you confirm which branch (`git branch`) and commit number (`git rev-parse HEAD`) you're encountering this bug on?

**Comment by HarrisNami** [comment]
Sorry i should have been more specific, it is on the ROI branch and the commit number is 870a952da47b1b5dbabbe93f06c42bd38ada7714 (is that right? I just did git rev-parse HEAD)

**Comment by mathieuboudreau** [comment]
@HarrisNami yup – thanks! I think since @TommyBoshkovski is working on that branch, he should be to look into that bug, but I just wanted to make sure.

**Comment by TommyBoshkovski** [comment]
@HarrisNami  The bug is fixed :)

**Comment by HarrisNami** [comment]
Yup it's working now, thanks @TommyBoshkovski
