### ISSUE TITLE
Compiling Faddeeva vs Using erfi 

### ISSUE THREAD

**Issue by agahkarakuzu** [neuropoly/qMRLab#224]
`startup.m` fails if a supported compiler is not installed on machine because `NODDI_erfi` is forced to use Faddeeva that needs a mex build. Exception handling in `startup.m` is based on _if mex lib is not built_, but the case _mex lib cannot be built_ is not handled. 
 
https://github.com/neuropoly/qMRLab/blob/3ad5358b7d4cb48d143fbfa9a5ad0c230ba17b2e/startup.m#L28-L43

Would that be ok to make a conditional use case (of those commented out lines in `NODDI_erfi.m`), so that functionality is sustained even if compiling cannot be done.  

https://github.com/neuropoly/qMRLab/blob/3ad5358b7d4cb48d143fbfa9a5ad0c230ba17b2e/External/NODDI_toolbox_v1.0/models/watson/NODDI_erfi.m#L1-L26

**Comment by mathieuboudreau** [comment]
> Would that be ok to make a conditional use case (of those commented out lines in NODDI_erfi.m), so that functionality is sustained even if compiling cannot be done.

If that's not possible, and a compiler *must* be used for NODDI, I'd recommend a conditional check such that if a compiler is not found to be installed in MATLAB (or Octave?), then skip it on startup.m and don't make that model available on the GUI (maybe throw a warning too?)

**Comment by mathieuboudreau** [comment]
Resolved in #239
