### ISSUE TITLE
Location and overwrite of FitResults folder

### ISSUE THREAD

**Issue by ileppe** [neuropoly/qMRLab#228]
1- by default, the `FitResults` folder is created in the current directory, wouldn't it make sense if it was written by default into the same directory as the input? We should probably have an option for changing this.

2- an older version of the code would create a new `FitResults` folder, with a different name, every time the fitting was run. Now it is overwritten every time, which is not  a good idea. Was this functionality removed for a particular reason?

**Comment by mathieuboudreau** [comment]
@ileppe Hmm, as for your first point, I just tried it using master and the vfa data, with my current directory being qMRLab/, and the FitResults folder was properly saved in my "working directory" (now called "Path Data") as it always has (/Users/mathieuboudreau/neuropoly/github/qMRLab/tmp/vfa_t1_demo/vfa_t1_data was my Path Data directory) . Did you set your "Path Data" directory in the GUI or leave it empty?

As for your second point, I do see that it is overwritten if I run it a second time. I'm not sure what change could have been made for this to happen, but can take a look.

**Comment by mathieuboudreau** [comment]
For your second point, for me the folder isn't overwritten, it's that the a second FItResults file is written in that folder (not overwritten, but with the index _2.mat, _3.mat, etc). That way there is one FitResults folder, and all your runs results will be in it. Would you prefer multiple folders instead? Not sure if/when this was changed, but using the blame feature it looks like it might have been @tanguyduval in the GuiFixes pull requests two months ago (can't tell for sure since the commits were squashed): https://github.com/neuropoly/qMRLab/blame/3ad5358b7d4cb48d143fbfa9a5ad0c230ba17b2e/qMRLab.m#L374-L391

**Comment by ileppe** [comment]
1- @mathieuboudreau I see. I would think leaving it blank would by default write to the input dir. But this is not a huge issue (`Path Data` is still a little confusing, I should probably update the GUI help on the documentation, even though it is clear once you press on the `?`).
2- You're right, the folder is not overwritten but the nii files are (I think they should be kept). I liked the old way, with the date, so you could easily keep track of your runs, what do you think?

**Comment by mathieuboudreau** [comment]
1 – @ileppe I think the issue with writing it in the input directory comes down to this: which input directory? If you have a method that has 3 data input (e.g. VFA data, B1 data, Mask), and all of these are in different folders, which folder should it be saved in? Natural instinct might say the VFA data folder, but this gets complicated in other methods where there are more than one required data folder (e.g. MTsat has PDw, T1w, and MTw data paths, each of which could be in different folders...)

2- I like the idea of having a single FitRestults folders (I don't really see the point of having multiple folders if they all only contain a single file), but am open to setting more descriptive auto-FitResults_(date/time).mat names. What do you think of this pattern?

**Comment by ileppe** [comment]
1- Ok, I'm ok with the way it is now
2- I would like to have nii files saved every time I run a fit, so not just a folder with a single .mat file (almost all models output more than 1 fitted file). The viewer in the GUI is a little clonky so I like to be able to open it elsewhere...

**Comment by mathieuboudreau** [comment]
2-Ah ok, that workflow makes sense to me now! I forgot that the fitted files were ouputted as *.nii's . I'll try to make a fix and will put you as a reviewer in the pull request.
