### ISSUE TITLE
qMRGenBatch: How is the sensitivity analysis plotted variable chosen?

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/qMRLab#244]
@agahkarakuzu you're the one who wrote qMRGenBatch right? If so this question is for you.

I ran qMRGenBatch for two models today, `inversion_recovery` and `vfa_t1`.

For IR, the sensitivity analysis plot (fig 4) of the generated script showed me what I expected (Fitted T1 vs input T1).

![fig4](https://user-images.githubusercontent.com/1421029/42232284-83eb0bc2-7ec8-11e8-9601-518d596efd00.png)

For VFA, the sensitivity analysis plot didn't show me the variable that I as a user would have wanted to see (it showed me M0 vs M0).

![fig4_2](https://user-images.githubusercontent.com/1421029/42232289-89476c96-7ec8-11e8-90e1-961a85084ba9.png)

What influences which variable is chosen in the qMRGenBatch for the sensitivity analysis to be performed, and how can we change it so that it is always a specific parameter of interest (in this case, for T1 mapping methods, show sensitivity for the T1 vals)? I tried looking in the qMRGenBatch code, but it was a little bit to abstract for me at first glance.

**Comment by tanguyduval** [comment]
'M0' is certainly the first variable defined in Model.xnames. Careful: you
have to invert the order everywhere in vfa_t1.m (obj.lb, obj.ub,  obj.st,
obj.fx).
.

Le mar. 3 juil. 2018 à 18:24, Mathieu Boudreau <notifications@github.com> a
écrit :

**Comment by mathieuboudreau** [comment]
Ah ha that makes sense, thanks @tanguyduval ! Maybe this should be documented in the wiki for developpers when creating new models (i.e. make the first variable in Model.xnames the most likely "interesting" variable of your model).

I'm curious to check if this could also be improved in any other models.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau `qMRgenBatch` calls `qMRusage` to retrieve commands for sensitivity analysis and single voxel curve. As @tanguyduval mentioned and you noted, documenting an ordering rule for independent variables is necessary.

To that end, I tried to [explain it](https://github.com/neuropoly/qMRLab/wiki/Guideline:-Adding-a-new-Model#-property-2-xnames) in my half-baked adding a new model guideline.

**Comment by tanguyduval** [comment]
Thanks Agah, great wiki

**Comment by mathieuboudreau** [comment]
@agahkarakuzu ah ha, thanks Agah! I should have checked to see if it was already there before suggesting it ;)
