### ISSUE TITLE
Ideas for INCF Hackathon 

### ISSUE THREAD

**Issue by agahkarakuzu** [neuropoly/qMRLab#251]
The theme of this hackathon is going to be interoperability. From a previous thread, I picked Greg's description:

> Taking existing standards/projects/tools/etc., and extending them to "play-nice" with others.

Thinking of extending the qMRLab to play nice with others, first thing that comes to my mind is preprocessing workflows. In other words, making  qMRLab workflow friendly, as @mathieuboudreau and I tried to make it BIDS friendly in a previous hackathon. 

Feel free to bring in more ideas, it can be related to any standard/project/tool that you think might be useful to work with.

**Comment by mathieuboudreau** [comment]
Maybe we could explore trying to get qMRLab and another pre-processing tool like SPM to work together, since we don't currently have any pre-processing (e.g. registration, brain extraction) done in qMRLab?

**Comment by agahkarakuzu** [comment]
@mathieuboudreau I agree, a Matlab based tool would come in handy. How do you feel about using PSOM for sequencing SPM + qMRLab? 

@ileppe  shared some raw data with me (VFA if I am not mistaken) for the previous hackathon, but I could not make it up to that point.

**Comment by mathieuboudreau** [comment]
By PSOM you mean this repo? https://github.com/SIMEXP/psom

Sure we could try it - have you used it before?

**Comment by agahkarakuzu** [comment]
Indeed, that one. I have not used it before, but I know that it has some advantages over scripting. For example, it generates workflow diagrams, goes multicore auto if possible and can restart from the last successful execution step if operation was somehow interrupted.

**Comment by mathieuboudreau** [comment]
Ok! That could be a fun tool to explore!

**Comment by jcohenadad** [comment]
PSOM is nice but it adds a layer of complexity for novice users (typical profile: knows SPM/FSL, uses the GUI, processes one subject at a time). IMHO it is more urgent to provide comprehensive preprocessing options to these users (i.e. focus on SPM only), instead of trying to bring PSOM into the equation (at that point).

**Comment by agahkarakuzu** [comment]
@jcohenadad I see. As for providing comprehensive preprocessing options with SPM, would output of this be more like a tutorial for a single subject case or integration of SPM modules?

**Comment by jcohenadad** [comment]
More like tutorial. Do we have any quantitative idea about our users profiles? (Number of users, GUI, number of subj they process, what preproc needs, etc.)?
