### ISSUE TITLE
Create Wiki based off of ReadMe.docx

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/qMRLab#26]
This is just a heads up to all that I intend to move the information from ReadMe.docx into a GitHub wiki. It seems that there are new features being continuously created for the software, and it would be great if information about these new features and how to use them could be added to the Wiki documentation as the project moves along. In addition, the Wiki lends itself better to version control than the *.docx filetype.

I'll probably start off by simply cutting and pasting more of the information from the *.docx into different Wiki pages, and from then on we can update any of those pages if the information is outdated (which is probably likely, since the *.docx was last updated 10 months ago).

Cheers,

Mathieu

**Comment by jfcabana** [comment]
That's a very good idea. Thanks for your initiative!
