### ISSUE TITLE
rename project to qMRLab

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/qMRLab#34]
suggestion from Nikola.
Open to discussion

**Comment by mathieuboudreau** [comment]
I'm indifferent, but let's pick one and stick to it for a while, so that I don't have to frequently rename all the other projects that I've included qMRILab as a submodule haha.

**Comment by tanguyduval** [comment]
I agree with Mathieu, it's additional work to change name, in particular in the code.

**Comment by nstikov** [comment]
I do feel strongly, as qMRILab is impossible to pronounce. Also, qMRLab is a very nice follow up to qMTLab (one letter change), and typographically it looks nicer.

**Comment by jcohenadad** [comment]
sorry guys, no more change after that, we promise ;-)

**Comment by tanguyduval** [comment]
We changed the name on Ian computer. He needs to finish testing all his modifications and testing before pushing the new name.

**Comment by mathieuboudreau** [comment]
When do you anticipate the github repo name itself will be changed?

**Comment by tanguyduval** [comment]
@alexfoias Monday 2pm is ok?

**Comment by alexfoias** [comment]
@tanguyduval ok for 2017-06-26 at 2pm

**Comment by mathieuboudreau** [comment]
@alexfoias @tanguyduval Did something go wrong/delayed it?

**Comment by tanguyduval** [comment]
@mathieuboudreau  Sorry, I was too much in a rush. Ian didn't totally finished his modifications. I'll change the name with Alex tomorrow 2pm.
Best,
Tanguy

**Comment by mathieuboudreau** [comment]
No problem Tanguy, thanks for the update!

**Comment by alexfoias** [comment]
@mathieuboudreau  I have changed the name, please do a new clone of the repo

**Comment by alexfoias** [comment]
@neuropoly/qmtlab The repo was renamed please do a fresh clone of it.

**Comment by mathieuboudreau** [comment]
I don't see why I need to do a new clone of the repo, only change the remote location, right?

https://stackoverflow.com/questions/30443333/error-with-renamed-repo-in-github-remote-this-repository-moved-please-use-th/30443593

**Comment by alexfoias** [comment]
Yes you can also do a change remote location.

--
Alexandru Foias MScA

Research Associate
Institute of Biomedical Engineering, Polytechnique Montréal
2900 Edouard-Montpetit Bld, room L-5626
Montreal, QC, H3T1J4, Canada
Phone: +1 (514) 340-4711 (office: 7546) <+15143404711> ;  Skype: alexfoias
E-mail: alexandru.foias@polymtl.ca
Web: www.neuro.polymtl.ca

**Comment by mathieuboudreau** [comment]
Thanks for everything, Alex!
