### ISSUE TITLE
Missing test data file

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/qMRLab#40]
Hey Ilana (@ileppe)!

I took a look at the unit test you just committed; it appears that you forgot to commit the test data file somewhere in the repo, such that the script doesn't run for me when I pulled the latest commits: https://github.com/neuropoly/qMRLab/blame/f437de271f2b46c68ef13d4c6a61ce2b866a05a7/Models_Functions/IRfun/utest.m#L2

Cheers,

Mathieu

**Comment by ileppe** [comment]
Hi Mathieu,
I've uploaded the demo data in the 'Data/IR_demo' folder. You can discard my unit test.
