### ISSUE TITLE
Gamma bar units choice?

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/qMRLab#44]
Hi Jean-Francois @jfcabana,

I was just curious to know if there was a technical/computational reason as to why you chose to express gamma-bar (gamma divided by 2Pi: [here_1](https://github.com/neuropoly/qMRLab/blob/fc8b0ed61e782fa53d9f89757028a31345716745/Common/computeAmp.m#L8), [here_2](https://github.com/neuropoly/qMRLab/blob/fc8b0ed61e782fa53d9f89757028a31345716745/Common/sim/BlochSol.m#L5), and [here_3](https://github.com/neuropoly/qMRLab/blob/fc8b0ed61e782fa53d9f89757028a31345716745/Common/pulse/GetPulse.m#L3))  in kHz/T (`42576`) instead of MHz/T ([42.576](https://en.wikipedia.org/wiki/Gyromagnetic_ratio#For_a_nucleus))?

**Comment by jfcabana** [comment]
Hi Mathieu,

I don't think there is a computational reason. Some parts of my code were taken from the legacy qMTLab code, and I just followed along with what was used there for consistency. Maybe that was to be in the same scale as MT pulse offset? I couldn't tell :P

Cheers!

**Comment by mathieuboudreau** [comment]
Ok I'll take a look at the old code to see if it's there too. 

I was thinking it might be useful to create a struct and/or class to handle all the constants in a single location, that way some of these magic numbers will be less mysterious and more easily modifiable.

Thanks!
