### ISSUE TITLE
Issue with MWF noise calculation

### ISSUE THREAD

**Issue by IanGagnon7** [neuropoly/qMRLab#49]
We noticed that `multi_comp_fit.m` has a very poor way to estimate the sigma of the noise 
```
function sigma = calc_bkgrnd_noise(data_vol, data_dim)

slices = data_dim(1,3);
height = data_dim(1,1);
width = data_dim(1,2);
voxels = height*width;
num_echoes = data_dim(1,4);

%--------------------------------------------------------------------------
% Calculate background noise 

% "default" noise level...
sigma(1:slices) = 1;

% Prepare noise mask
noise_mask = zeros(height,width,slices);

% Pick four corners of 5x5
noise_mask(1:5,1:5,:) = 1;
noise_mask(1:5,end-5:end,:) = 1;
noise_mask(end-5:end,1:5,:) = 1;
noise_mask(end-5:end,end-5:end,:) = 1;

% apply mask to the data
for slice = 1:slices
    for frame = 1:num_echoes
        noise_data(:,:,slice,frame) = data_vol(:,:,slice,frame).*noise_mask(:,:,slice); 
    end
end

noise_data = reshape(noise_data, voxels, slices, num_echoes);

for slice = 1:slices
    for frame = 1:num_echoes
        std_noise(slice,frame) = std(nonzeros(noise_data(:,slice,frame)));
    end
end

for slice = 1:slices
    sigma(slice) = mean(std_noise(slice,:));
end

end
```

Indeed, it simply picks the 4 corners of MET2 data, finds the standard deviation (std) for each slice and takes the mean of all std. Instead of that, we propose to use PIESNO algorithm to estimate the noise and therefore find sigma. https://www.ncbi.nlm.nih.gov/pubmed/19346143
To do so, there are 2 main possibilities:
1) Ask Koay (the author) to obtain his Java script and consent to add it to qMRLab
2) Directly implement the algorithm in Matlab

Let me know what's best! @jcohenadad @tanguyduval  @mathieuboudreau 
Ian

**Comment by tanguyduval** [comment]
Thanks for this investigation Ian,

First of all:
- Plz add sigma has an option for MWF
-  Create a new ''Model'' Noise/NoiseLevel.m. Inputs: 4Ddata, NoiseMask. Voxelwise=0; Output: sigma. You can fit the noise histogram using a function like https://www.mathworks.com/matlabcentral/fileexchange/54244-histfit-noncentralchi

Concerning PIESNO.
Koay shares his code here: https://sites.google.com/site/hispeedpackets/
It's a java code so it's compatible with Matlab (a Matlab example already exists). However:
```
This archive does not contain the jar file, which is needed to "run" the software packets.
To obtain this jar file (compiled using Java JDK 1.7), your statement of consent to the software agreement is needed.
```

So in my opinion
1- Ask Koay if he agrees to share the code for qMRLab
2- If not implement it.
In the future, we will create a model Noise/PIESNO.m. Input: 4d Data. Output: NoiseMask, sigma.

Best
