### ISSUE TITLE
Documentation: Use sphinx

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/qMRLab#57]
@ileppe: contact Christian for porting the current doc into git.io with Sphinx. Example here: https://neuropoly.github.io/axondeepseg/documentation.html#creating-a-virtual-environment
@tanguyduval: work on the dev doc (have a look at https://github.com/neuropoly/spinalcordtoolbox/wiki)

**Comment by ileppe** [comment]
@tanguyduval @mathieuboudreau @IanGagnon7 
Hi guys, I started setting up the documentation with Sphinx. You can take a look by getting a copy of my branch 'doc' and loading this file into your browser:
https://github.com/neuropoly/qMRLab/blob/doc/Documentation/build/html/index.html
Eventually there will be a direct link to it through github.io. I grabbed text from other locations and I'm slowly integrating it. I think we soon have to decide how we want to go about it:
1. autodocumentation : automatically searches code for specific strings (not convinced this is worth it)
2. links to 'batch_example.m' scripts
3. post matlab code directly
Let me know what you think!
Thanks!
Ilana

**Comment by ileppe** [comment]
Forgot to mention, please look at the Inversion Recovery section for an example of the auto-documentation (last section) and some ideas about the other stuff that should be added (usage, citation, etc.). Thanks!

**Comment by tanguyduval** [comment]
Very nice Ilana!

My recommandations:
- go with links to batch
- Describe in a section a description of the common methods and their usage (e.g. equation, plotmodel, fit, Sim...)
- give global overview of qMT methods (2 pools, 3 pools, on resonance, off resonance), diffusion methods (2d/3d qspace, single/multi shells, Gaussian/non-Gaussian, Composite Hindered and restricted)... and redirect to class help for more info about each model.
- add nice screenshots :)

**Comment by tanguyduval** [comment]
For the usage section, I'm starting a MATLAB function that you could use with autodocumentation.

**Comment by ileppe** [comment]
Hi Tanguy,

   - go with links to batch

ok

   - Describe in a section a description of the common methods and their
   usage (e.g. equation, plotmodel, fit, Sim...)

this was done with autodocumentation for the example Inversion Recovery,
but I don't find it that nice. Are you suggesting we write it up for every
model?

   - give global overview of qMT methods (2 pools, 3 pools, on resonance,
   off resonance), diffusion methods (2d/3d qspace, single/multi shells,
   Gaussian/non-Gaussian, Composite Hindered and restricted)... and redirect
   to class help for more info about each model.

ok, I'll try to write something, I'm not an expert in all of these though!

   - add nice screenshots :)

OK


This is how my matlab function looks like for autodocumentation... it's a
bit annoying...:
https://github.com/neuropoly/qMRLab/blob/doc/Models/T1_Mapping/InversionRecovery.m


Merci pour les inputs!
Ilana
---------------------------------
Ilana Leppert
Brain Imaging Center
Montreal Neurological Institute
3801 University St. Rm WB325, Montreal
Qc, Canada
tel: 514-398-8547

**Comment by jcohenadad** [comment]
@ileppe: very nice indeed. How come the header of the InversionRecovery.m file does not appear in the autodoc? (maybe that was related to Tanguy's comment "Describe in a section a description..."?).
I think we should definitely go with the autodoc approach. By experience, this will help us in the long term even though it's a bit of a pain to establish this convention.

**Comment by tanguyduval** [comment]
Julien was right, we are going to forget to update the Models header when adding an option (I just did it with SPGR...).
@gab-berest or @ileppe could you plz create a function to parse the Model header. And then create a test to check if all options and xnames are described in the header. This function could also be used to display the help nicely on sphinx (via Travis).
Does everyone agree with this strategy?

Here are the list of functions that would be needed to perform this:
- `which` to find the .m file associated with each Model
- `fopen` to open the file
- `fgetl` to read line by line (until the first character is not %)
- `strfind` or `regexp` to detect a particular expression

We can keep the old header format (used in all methods except InversionRecovery) if we go that way

**Comment by tanguyduval** [comment]
If not done by anyone yet, @gab-berest could write a function to parse the header (see previous message). This is a higher priority than looking at mex files.
Thanks!
