### ISSUE TITLE
Use TRAVIS with Octave

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/qMRLab#59]

**Comment by tanguyduval** [comment]
travis-ci.org

**Comment by tanguyduval** [comment]
https://github.com/MOxUnit/MOxUnit

**Comment by mathieuboudreau** [comment]
@tanguyduval that looks pretty similar to Matlab's unit testing framework that I've been using up to date. If Matlab's built-in class/function-based framework isn't compatible with Octave, that looks like a great alternative.

I don't imagine it would be too much trouble converting my current unit tests to this framework.

**Comment by tanguyduval** [comment]
Exactly. Currently I just used their travis config file. If current unit test is not compatible with octable, will switch to this option (MoxUnit).

**Comment by tanguyduval** [comment]
Ok, I started to clear out the situation. We have 2 options:

1- use a local CI service such as Jenkins to run the tests:
https://blogs.mathworks.com/developer/2015/01/20/the-other-kind-of-continuous-integration/
Pros: - MATLAB can perform the tests. No further development 
- flexibility. e.g. Jenkins can be used to compile scripts continuously

2- use MOxUnit and Travis. For this option we have to reformat all the testing class to testing function...  We can add MOxUnit as a submodule in the External folder.
Pros: - Guarantee compatibility with Octave. Useful if we want to use Jupiter Notebook.
- No need to maintain a dedicated computer for testing

I would go for option 2, meaning we have to change tests scripts..

**Comment by mathieuboudreau** [comment]
@tanguyduval I agree, it sounds like it makes more sense to try option number 2. I don't know how much time I'll have this week to convert the tests, but I'll try to do a couple so that you can at least test them with TRAVIS.

**Comment by tanguyduval** [comment]
I wrote a test script that calls the Simulation for all Models:
https://github.com/neuropoly/qMRLab/tree/Dev/Test/MoxUnitCompatible

This test passes correctly on Travis.
this test calls equation, plotmodel, fit + simulation.
It compares the input of the simulation with the output, assuming less than 20% error:

````
 [~,FitResults,GroundTruth]=comp_struct(FitResults,mat2struct(st,Model.xnames),[],[],.20);
````

I had to switch `Integral` to `quad`, and `random('rician' ...`  and `pdf('rician'` to an external function found on fileexchange

**Comment by tanguyduval** [comment]
3 tests have been written, (run only for voxelwise methods):
- test modelplot
- test equation for consistency across versions. Relative error of 1% on the signal tolerated for differences between Octave and Matlab.
- test fitting using SimSingleVoxelCurve

Travis configuration is done.
Dev is passing: https://travis-ci.org/neuropoly/qMRLab
Travis install octave and necessary packages, then run the tests in folder Test/MoxUnitCompatible

**Comment by tanguyduval** [comment]
done
