### ISSUE TITLE
[MTSAT] current script give absurd values

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/qMRLab#62]
MTsat value should be <1. Currently values are up to 10000 in the WM...

**Comment by tanguyduval** [comment]
I used Simon MTSAT equation in this commit 989879e75e4494b609020f54cdef7967f07bcbe5
@BeliveauP can you check the equation. Note that there were an erratum in Helms paper.
You can ask @slevyrosetti if you have questions about his implementation

**Comment by tanguyduval** [comment]
I think with his code we should be able to replace T1w with T1. An option could be added to enable this feature.

**Comment by mathieuboudreau** [comment]
Great catch Tanguy! Once this bug is resolved, it would be nice if a test could be written that would have failed under the old method, and passes after the fix, in case it reappears in the future. Or did you discover it while already writing such a test for TRAVIS?

**Comment by tanguyduval** [comment]
I'm going over all the examples and I saw many errors that I'm solving now. My idea would be to write a test that calls the batch of each Model and compare fitting results.

**Comment by nstikov** [comment]
Has this been resolved? Thanks for catching it!

**Comment by nstikov** [comment]
Ilana has also been looking into computing MT_sat from MP2RAGE. The problem
is that T1 maps generated from MP2RAGE are very different from SPGR T1
maps, so the MT_sat maps also look different. Not sure we have a good
solution for this, but understanding the absurd values is a start.

**Comment by BeliveauP** [comment]
@tanguyduval @ileppe @nstikov 
A branch has been created MTsatModif which includes initial modifications.

**Comment by BeliveauP** [comment]
@tanguyduval @ileppe @nstikov 
I've compared MTsat results between Ilana's script and the output of qMRLab, using a dataset she shared with me. The results are the same after changing for percent units in qMRLab: MTsat*100 (in branch MTsatModif). It would be ok to merge the branch.
