### ISSUE TITLE
"Myelin Imaging" --> "MyelinImaging"

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/qMRLab#63]
never use space in folder and file names (UNIX unfriendly).

wiki here: https://github.com/neuropoly/qMRLab/wiki/file_name

**Comment by jcohenadad** [comment]
actually this raises another question: don't we want to use "lower camel case" instead of "bigger camel case", i.e., inversionRecovery vs. InversionRecovery. Because user doesn't need to press "shift" each time he/she wants to call a function, and autocompletion will help doing the rest of the job.

**Comment by mathieuboudreau** [comment]
@jcohenadad I think one of the conventions for Matlab is to have class names start with an upper camel-case (e.g. InversionRecovery), and methods/functions are lower camel case lower camel-case (e.g. getValue).

That being said, I don't think qMRLab is following a camel-case convention consistently regardless; for example, the MTSAT class is completely uppercase: https://github.com/neuropoly/qMRLab/blob/master/Models/Myelin%20Imaging/MTSAT.m

**Comment by jcohenadad** [comment]
@mathieuboudreau got it!
wiki updated: https://github.com/neuropoly/qMRLab/wiki/file_name
