### ISSUE TITLE
IR doc links to batch example in Dev branch instead of Master

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/qMRLab#73]
The InversionRecovery module documentation links to a batch example under "Usage", however it points to the dev branch instead of master, [see this line](https://github.com/neuropoly/qMRLab/blob/d7d67c360927d4879c86399d4714dfcdf3a3f83c/Models/T1_Mapping/InversionRecovery.m#L6).

Do we agree that documentation should always point to files in Master, as Dev could get deleted/renamed in the future?

**Comment by jcohenadad** [comment]
i agree pointing to master would be better, however this is a bit tricky: if we don't ensure cross-compatibility across releases, someone working with v2.0.1 will click on this link and the master branch might produce different behaviour than what's expected from v2.0.1. 
Ideally, each time we publish a release, those links should point to the commit of the release.
We need to find an elegant solution for doing that (obviously not manually editing each link before the release...)

**Comment by mathieuboudreau** [comment]
Maybe instead of an http link to the Github repo, we could simply write a relative folder link in the Usage section of the module doc? It wouldnt be clickable on the web, but would indicate in which folder the batch file is located in, which they could then browse to on their own OS.

**Comment by mathieuboudreau** [comment]
Solved in 40f529 - thanks @ileppe !
