### ISSUE TITLE
Optional inputs in GUI

### ISSUE THREAD

**Issue by ileppe** [neuropoly/qMRLab#83]
Right now, the user can't tell which inputs are optional (e.g. Mask) on the GUI interface. We should add brackets or something, without messing up `MRIinputs`.

**Comment by jcohenadad** [comment]
Right. In the header of CHARMED I've introduced brackets for optional inputs. In the GUI we can play with colors.

**Comment by tanguyduval** [comment]
We need the header parser for that. Last message in issue #57

**Comment by ileppe** [comment]
solved in 4debca2
