### ISSUE TITLE
GUI: Name of model is cropped

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/qMRLab#85]
This is a pretty fundamental information. We should find a way to better display it. Maybe by removing the "Myelin Imaging" before, and instead display category inside the combobox.

![screen shot 2017-10-19 at 07 39 20](https://user-images.githubusercontent.com/2482071/31769250-dff0c22e-b4a0-11e7-9141-4c4250e4558f.png)

**Comment by mathieuboudreau** [comment]
I agree, I don't think the "myelin imaging" section is really needed in the list, particularly since some of those techniques have applications beyond this.

**Comment by tanguyduval** [comment]
Solved in ??? a few weeks ago. Already merged on Master
