### ISSUE TITLE
Remove "RGB" component

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/qMRLab#88]
See: 
<img width="255" alt="screen shot 2017-10-19 at 08 00 24" src="https://user-images.githubusercontent.com/2482071/31769938-9e3f9834-b4a3-11e7-93dd-72ff5d563949.png">

I don't think this is used in any model. @tanguyduval do you confirm?

**Comment by tanguyduval** [comment]
I confirm, RGB is useless
