### ISSUE TITLE
Adjust bins in histogram

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/qMRLab#89]
Otherwise it is useless. See below for MTSAT example:
<img width="1367" alt="screen shot 2017-10-19 at 08 01 38" src="https://user-images.githubusercontent.com/2482071/31769984-cc3d7a8a-b4a3-11e7-941e-cca5993327ae.png">

**Comment by mathieuboudreau** [comment]
Another suggestion I would have is having the option to plot normalised histograms, since it's easier to compare than the counts.

**Comment by tanguyduval** [comment]
#123
Histogram.m has an auto-bin selection algorithm but is not compatible with old version of Matlab (<R2014b) 
https://fr.mathworks.com/help/matlab/creating_plots/replace-discouraged-instances-of-hist-and-histc.html 
Reuse the same algorithm (look at BinMethod)

For the normalization, just add a button `uicontrol`
