### ISSUE TITLE
ROI functionality is obscure

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/qMRLab#91]
- User clicks on a "Draw" method
- User makes a nice ROI on the figure
... and what next? When clicking on "histogram", one thinks that it is computed within the ROI, but this is not the case. There should be ROI-specific basic computations such as histo, mean, STD, etc.

**Comment by jcohenadad** [comment]
remove ROI functionality from now

**Comment by tanguyduval** [comment]
done in 6b0c9d0fb6235ba9e8643d98ddc3cd356f6c5a87

**Comment by jcohenadad** [comment]
can you open a PR?
