### ISSUE TITLE
Data selection: information about "Work Dir"

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/qMRLab#92]
It was not clear to me that the "Work Dir" referred to where the data are located (and subsequently selected automatically). I would call it "Path data" or something like that, and I would add a help info "?", that would tell the users that if he/she has data named appropriately (MTw.nii.gz, etc.), then they are automatically selected.

**Comment by tanguyduval** [comment]
![image](https://user-images.githubusercontent.com/7785316/38031862-87e9662e-329c-11e8-8760-486b638272ca.png)
