### ISSUE TITLE
"Open viewer" functionality is unclear

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/qMRLab#93]
Here's what i get when i click on "Open viewer":
<img width="1134" alt="screen shot 2017-10-19 at 08 36 53" src="https://user-images.githubusercontent.com/2482071/31771085-bb1ed960-b4a8-11e7-8205-eb83c62e6c87.png">

**Comment by tanguyduval** [comment]
Close and restart qMRLab to solve this issue. Might be unstable when too many buttons were called.
