### ISSUE TITLE
"View fitted data" button asks to select a voxel when it's already checked

### ISSUE THREAD

**Issue by gab-berest** [neuropoly/qMRLab#95]
The "View fitted data" button asks to select a voxel before looking into it. You have to push select and select the voxel another time for it to work.

**Comment by gab-berest** [comment]
@jcohenadad  Hi, I'll have to check with you for this issue because it doesn't give me the issue on my side.

**Comment by jcohenadad** [comment]
indeed, for some reasons i cannot reproduce this error. So i get we can close for now
