### ISSUE TITLE
IR data do not load automatically even if path is correct

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/qMRLab#97]
https://www.dropbox.com/s/l998339vn1864xp/20171029_qMRLab_IRLoad.m4v?dl=0

**Comment by tanguyduval** [comment]
thanks for reporting this. Working directory is case sensitive. Done in 521e403303284748e36a2419b555930bd0e6f02d (sorry I pushed directly to master, I skipped the pull request for that)
